steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/stock-scanner:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/stock-scanner:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'stock-scanner'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/stock-scanner:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--concurrency'
      - '1'
      - '--max-instances'
      - '1'
      - '--set-env-vars'
      - 'TWELVEDATA_API_KEY=$_TWELVEDATA_API_KEY,APCA_API_KEY_ID=$_APCA_API_KEY_ID,APCA_API_SECRET_KEY=$_APCA_API_SECRET_KEY,APCA_BASE_URL=https://paper-api.alpaca.markets,ALPACA_MAX_NOTIONAL=10000,DB_HOST=$_DB_HOST,DB_PORT=5432,DB_NAME=$_DB_NAME,DB_USER=$_DB_USER,DB_PASSWORD=$_DB_PASSWORD,DB_SSLMODE=require,GITHUB_TOKEN=$_GITHUB_TOKEN,GITHUB_REPO=alpaca-trade-logs,GITHUB_OWNER=$_GITHUB_OWNER,GITHUB_BRANCH=main,ENABLE_DB_LOGGING=true,ENABLE_ALPACA_HTTP_AUDIT=true'
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/stock-scanner:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
